export const RCL_BOOTSTRAP_MIN = 2;

export const DIRECTION_TO_OFFSET = [
  0, 0,   // CENTER
  0, -1,  // TOP
  1, -1,  // TOP_RIGHT
  1, 0,   // RIGHT
  1, 1,   // BOTTOM_RIGHT
  0, 1,   // BOTTOM
  -1, 1,  // BOTTOM_LEFT
  -1, 0,  // LEFT
  -1, -1, // TOP_LEFT
];

export const OFFSET_TO_DIRECTION = [
  TOP_LEFT, TOP, TOP_RIGHT,
  LEFT, 0, RIGHT,
  BOTTOM_LEFT, BOTTOM, BOTTOM_RIGHT,
];

export const MATRIX_LAYER_TERRAIN = 0;
export const MATRIX_LAYER_STRUCTURES = 1;
export const MATRIX_LAYER_TUNNELS = 2;
export const MATRIX_LAYER_ROADS = 4;
export const MATRIX_LAYER_OFF_ROADS = 8;
export const MATRIX_LAYER_SWAMP_ROADS = MATRIX_LAYER_ROADS | MATRIX_LAYER_OFF_ROADS;
export const MATRIX_LAYER_CONTAINERS = 16;
export const MATRIX_LAYER_PREFER_CONTAINERS = 32;

export const MATRIX_CACHE_TIME = 50;

export const TARGET_LINE_COLOR = '#5ec8ff';

export const TERRAIN_COST = {
  0: 2,
  [TERRAIN_MASK_SWAMP]: 10,
  [TERRAIN_MASK_WALL]: 255,
  [TERRAIN_MASK_WALL | TERRAIN_MASK_SWAMP]: 255,
};

export const ROOM_PATTERN_HIGHWAY = /^[WE][0-9]?0[NS][0-9]?0$/;
